close all; clc;
TargetScale=484;%resize the image into target scale, where 484 is applied at the middle scale and 896 at the smallest scale. (see the paper for further information)
Image=imresize(imread('image.jpg'),[TargetScale TargetScale]);%load image
DisMap=imread('dismap.jpg'); %load the DisMap that has been generated by DisMap_generation.py for the corresponding image.
MapSize=length(DisMap);
ratio=TargetScale./MapSize;
T=100;%specify the threshold (see the paper for details)

%%
%crop patches with the size of 224x224 in a sliding window manner
for r_pos=2:MapSize-1
    for c_pos=2:MapSize-1
    SlidingWindow=MapSize(r_pos-1:r_pos+1,c_pos-1:c_pos+1);
    center=SlidingWindow(2,2);
    if (max(SlidingWindow(:))==center && center>T)
        cnt=cnt+1;        
        r_pos_img=ratio*r_pos;
        c_pos_img=ratio*c_pos;
        [r_left,r_right]=padding_operation(r_pos_img,TargetScale);
        [c_left,c_right]=padding_operation(c_pos_img,TargetScale);

        patch=Image(r_left:r_right,c_left:c_right,:);
        imwrite(patch,[num2str(center),'_',num2str(cnt),'.jpg'],'jpg');
        
    end
    end
end

